sudo: required
language: java
jdk: oraclejdk8

addons: 
  sonarcloud: 
    organization: divyakeerthana97-github
    token: 
      secure: f2c90a23b2d271fc050c347f4b7f63d858b4c411

before_install:
- chmod +x mvnw

script:
- "mvn clean install"
# - "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"

cache:
  directories:
  - "$HOME/.m2/repository"
  # - "$HOME/.sonar/cache"
